/** @format */

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import test from "../public/Feature3.svg";
import Link from "next/link";
import styled from "styled-components";
import { motion } from "framer-motion";
import React, { useState } from "react";
import {
	AppstoreOutlined,
	MailOutlined,
	SettingOutlined,
} from "@ant-design/icons";
import { Menu } from "antd";

const MyDiv = styled.div`
	border: 1px solid green;
	display: flex;
	flex-direction: column;

	padding: 30px;
	margin: 20px;
	.ant-menu-title-content {
		&:hover {
			background-color: pink;
		}
	}
	.ant-menu-horizontal {
		line-height: 46px;
	}
	.ant-menu-horizontal > .ant-menu-item-selected a {
		color: green;
	}
`;
export default function Home() {
	const items = [
		{
			label: "Navigation One",
			key: "mail",
			icon: <MailOutlined />,
		},
		{
			label: "Navigation Two",
			key: "app",
			icon: <AppstoreOutlined />,
			disabled: true,
		},
		{
			label: "Navigation Three - Submenu",
			key: "SubMenu",
			icon: <SettingOutlined />,
			children: [
				{
					type: "group",
					label: "Item 1",
					children: [
						{
							label: "Option 1",
							key: "setting:1",
						},
						{
							label: "Option 2",
							key: "setting:2",
						},
					],
				},
				{
					type: "group",
					label: "Item 2",
					children: [
						{
							label: "Option 3",
							key: "setting:3",
						},
						{
							label: "Option 4",
							key: "setting:4",
						},
					],
				},
			],
		},
		{
			label: (
				<a href='https://ant.design' target='_blank' rel='noopener noreferrer'>
					Navigation Four - Link
				</a>
			),
			key: "alipay",
		},
	];

	const [current, setCurrent] = useState("mail");

	const onClick = (e) => {
		console.log("click ", e);
		setCurrent(e.key);
	};

	const draw = {
		hidden: { pathLength: 0, opacity: 0 },
		visible: (i) => {
			const delay = 1 + i * 0.5;
			return {
				pathLength: 1,
				opacity: 1,
				transition: {
					pathLength: { delay, type: "spring", duration: 1.5, bounce: 0 },
					opacity: { delay, duration: 0.01 },
				},
			};
		},
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					<Image src={test} width='300' height='300' alt='test' />
					<Image
						src='https://via.placeholder.com/600x400.png'
						width='300'
						height='300'
						alt='test'
					/>
					<Image
						src='https://www.fillmurray.com/640/360'
						width='300'
						height='300'
						alt='test'
					/>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>
				<p className={styles.description}>
					Get started by editing{" "}
					<code className={styles.code}>pages/index.js</code>
				</p>
				<div className={styles.grid} style={{ backgroundColor: "#FF6F00" }}>
					<a href='https://nextjs.org/docs' className={styles.card}>
						<h2>Documentation &rarr;</h2>
						<p>Find in-depth information about Next.js features and API.</p>
					</a>

					<a href='https://nextjs.org/learn' className={styles.card}>
						<h2>Learn &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</a>
					<Link href='https://github.com/vercel/next.js/tree/canary/examples'>
						<a
							href='https://github.com/vercel/next.js/tree/canary/examples'
							className={styles.card}
						>
							<h2>Examples &rarr;</h2>
							<p>Discover and deploy boilerplate example Next.js projects.</p>
						</a>
					</Link>
					<a
						href='https://github.com/vercel/next.js/tree/canary/examples'
						className={styles.card}
					>
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</a>

					<a
						href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						className={styles.card}
					>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a>
				</div>
				<MyDiv>
					<h1>test</h1>
					<p>my test of styled component</p>
					<span>op 1</span>
					<span>op 2</span>
					<Menu
						onClick={onClick}
						selectedKeys={[current]}
						mode='horizontal'
						items={items}
					/>
				</MyDiv>
				<motion.svg
					width='600'
					height='600'
					viewBox='0 0 600 600'
					initial='hidden'
					animate='visible'
				>
					<motion.circle
						cx='100'
						cy='100'
						r='80'
						stroke='#ff0055'
						variants={draw}
						custom={1}
					/>
					<motion.line
						x1='220'
						y1='30'
						x2='360'
						y2='170'
						stroke='#00cc88'
						variants={draw}
						custom={2}
					/>
					<motion.line
						x1='220'
						y1='170'
						x2='360'
						y2='30'
						stroke='#00cc88'
						variants={draw}
						custom={2.5}
					/>
					<motion.rect
						width='140'
						height='140'
						x='410'
						y='30'
						rx='20'
						stroke='#0099ff'
						variants={draw}
						custom={3}
					/>
					<motion.circle
						cx='100'
						cy='300'
						r='80'
						stroke='#0099ff'
						variants={draw}
						custom={2}
					/>
					<motion.line
						x1='220'
						y1='230'
						x2='360'
						y2='370'
						stroke='#ff0055'
						custom={3}
						variants={draw}
					/>
					<motion.line
						x1='220'
						y1='370'
						x2='360'
						y2='230'
						stroke='#ff0055'
						custom={3.5}
						variants={draw}
					/>
					<motion.rect
						width='140'
						height='140'
						x='410'
						y='230'
						rx='20'
						stroke='#00cc88'
						custom={4}
						variants={draw}
					/>
					<motion.circle
						cx='100'
						cy='500'
						r='80'
						stroke='#00cc88'
						variants={draw}
						custom={3}
					/>
					<motion.line
						x1='220'
						y1='430'
						x2='360'
						y2='570'
						stroke='#0099ff'
						variants={draw}
						custom={4}
					/>
					<motion.line
						x1='220'
						y1='570'
						x2='360'
						y2='430'
						stroke='#0099ff'
						variants={draw}
						custom={4.5}
					/>
					<motion.rect
						width='140'
						height='140'
						x='410'
						y='430'
						rx='20'
						stroke='#ff0055'
						variants={draw}
						custom={5}
					/>
				</motion.svg>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
